services:
  baihu-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: baihu-dev
    ports:
      - "8052:8052"
      - "5173:5173"
    volumes:
      - .:/app:Z
      - baihu-data:/app/data
      - baihu-node-modules:/app/web/node_modules
      - go-path:/go
    environment:
      - TZ=Asia/Shanghai
    stdin_open: true
    tty: true

volumes:
  baihu-data:
    name: baihu_dev_data
  baihu-node-modules:
    name: baihu_dev_node_modules
  go-path:
    name: baihu_dev_go_path
